version: '3.7'
services:
  geth-bootnode:
    hostname: geth-bootnode
    image: devnet-img:latest
    command:
      --nodekeyhex="a9008d8f6644247cd064c1856c241115bcf6aaedca2af71d4537626864025220"
      --networkid="9999"
      --nodiscover
      --ipcdisable
      --netrestrict="121.0.0.1/8"
    ports:
      - 30310:30310/udp
    networks:
      priv-eth-net:
  geth-node1:
    hostname: geth-node1
    env_file:
      - .env
    image: devnet-img:latest
    depends_on:
      - geth-bootnode
    container_name: geth-node1
    command:
      --bootnodes=${BOOTNODEADDRESS}
      --networkid="9999"
      --verbosity=6
      --allow-insecure-unlock
      --http
      --http.addr="0.0.0.0"
      --http.corsdomain="*"
      --mine
      --miner.etherbase=${ADDRESS1}
      --unlock=${ADDRESS1}
      --password=tmp/gethaccounts/node1/password --keystore=tmp/gethaccounts/node1/keystore
    ports:
      - 8545:8545
    networks:
      priv-eth-net:
  geth-node2:
    hostname: geth-node2
    image: devnet-img:latest
    depends_on:
      - geth-bootnode
    container_name: geth-node2
    command:
      --bootnodes=${BOOTNODEADDRESS}
      --networkid="9999"
      --verbosity=6
      --allow-insecure-unlock
      --http
      --http.addr="0.0.0.0"
      --http.corsdomain="*"
      --mine
      --miner.etherbase=${ADDRESS2}
      --unlock=${ADDRESS2}
      --password=tmp/gethaccounts/node2/password --keystore=tmp/gethaccounts/node2/keystore
    ports:
      - 8546:8545
    networks:
      priv-eth-net:
networks:
  priv-eth-net:
    driver: bridge
    ipam:
      config:
      - subnet: 121.0.0.1/8
