name: CI-Deploy
on:
  pull_request:
    types: [ labeled ]

jobs:
  deploy:
    if: ${{ github.event.label.name == 'Deploy' }}
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        
      - uses: adrielcodeco/docker-compose-run-action@v1
        with:
          compose-file: './compose.yaml'
          service: devnet

      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
        
      - name: Deploy
        run: npx hardhat run .hardhat/scripts/deploy.ts --network localhost
      
      - name: Run Tests
        run: npx hardhat test

      - name: Stop containers
        if: always()
        run: docker-compose -f "./compose.yml" down          
