name: CI
on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'Build' }}
    environment: TEST_ENV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-ethereum:latest
  deploy:
    if: ${{ github.event.label.name == 'Deploy' }}
    environment: TEST_ENV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: isbang/compose-action@v1.5.1
        with:
          up-flags: -d
          compose-file: './compose.yaml'
          services: devnet
      
      - name: Installing Nodejs packages
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Installing Hardhat
        run: npm install --save-dev hardhat
      # - name: Adding packages
      #   run: npm install --save-dev "@nomicfoundation/hardhat-network-helpers@^1.0.0" "@nomicfoundation/hardhat-chai-matchers@^2.0.0" "@nomicfoundation/hardhat-ethers@^3.0.0" "@nomicfoundation/hardhat-verify@^1.0.0" "@types/chai@^4.2.0" "@types/mocha@>=9.1.0" "@typechain/ethers-v6@^0.4.0" "@typechain/hardhat@^8.0.0" "chai@^4.2.0" "hardhat-gas-reporter@^1.0.8" "solidity-coverage@^0.8.1" "ts-node@>=8.0.0" "typechain@^8.2.0" "typescript@>=4.5.0"
      - name: Running Hardhat
        run: npx hardhat compile && npx hardhat run scripts/deploy.js --network devnet
        continue-on-error: true
        
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      # - name: Build new image from running container
      #   run: docker commit $(docker ps | grep devnet | awk '{print $1}') ${{ secrets.DOCKERHUB_USERNAME }}/go-ethereum:devnet_hardhat
      # - name: Pushing new image to registry
      #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/go-ethereum:devnet_hardhat
    
      # - name: Stop containers
      #   if: '!cancelled()'
      #   run: docker-compose -f "./compose.yaml" down
  testing:
    if: ${{ github.event.label.name == 'Test' }}
    environment: TEST_ENV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Running devnet/hardhat image  
        run: docker run -dit ${{ secrets.DOCKERHUB_USERNAME }}/go-ethereum:devnet_hardhat
      
      - name: Installing Nodejs packages
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
    
      - name: Installing yarn, hardhat
        uses: borales/actions-yarn@v4
        with:
          cmd: init --yes && add --dev hardhat
          dir: 'hardhat'
        continue-on-error: true
      
      - name: Hardhat unit test
        run: cd hardhat
      - name: Environment
        uses: actions/setup-node@v3
      - name: Test
        uses: ambersun1234/hardhat-test-action@v1
        with:
          network: devnet
          private_key: ${{ secrets.PRIVATE_KEY }}
          rpc_url: ${{ secrets.RPC_URL }}
      
      - name: Check runnig containers
        run: docker ps 
      - name: Stop containers
        if: '!cancelled()'
        run: docker stop $(docker ps -q)
